apiVersion: v1
kind: Service
metadata:
  name: sample-node-project-with-nginx
spec:
  type: LoadBalancer
  selector:
    app: sample-node-project-with-nginx
  ports:
  - port: 3333
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-node-project-with-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-node-project-with-nginx
  template:
    metadata:
      labels:
        app: sample-node-project-with-nginx
    spec:
      containers:
      - name: sample-node-project-with-nginx
        image: pawan1210/sample-node-project-with-nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
